import { NextRequest, NextResponse } from 'next/server';
import { handleGlobalError } from '../app/middlewares/globalErrorHandler';
import { dbConnect } from '../DB/dbConnect';

const catchAsync =
  (fn: any) =>
  async (req: NextRequest, context: any) => {
    try {
      await dbConnect();
      let body: any = {};
      let files: any = {};
      try {
        if (req.method !== 'GET' && req.method !== 'DELETE') {
          // Check content type to handle multipart/form-data later if needed
          const contentType = req.headers.get('content-type') || '';
          if (contentType.includes('application/json')) {
            body = await req.json();
          } else if (contentType.includes('multipart/form-data')) {
            const formData = await req.formData();
            for (const [key, value] of formData.entries()) {
              if (value instanceof File) {
                const bytes = await value.arrayBuffer();
                const buffer = Buffer.from(bytes);
                const filename = `${Date.now()}-${value.name.replace(/\\s+/g, '_')}`;
                
                // create path like public/image
                const fs = await import('fs');
                const path = await import('path');
                const uploadDir = path.join(process.cwd(), 'public', key); // key is usually 'image', 'media', 'doc'
                
                if (!fs.existsSync(uploadDir)) {
                  fs.mkdirSync(uploadDir, { recursive: true });
                }
                
                fs.writeFileSync(path.join(uploadDir, filename), buffer);
                
                if (!files[key]) files[key] = [];
                files[key].push({ filename });
              } else {
                body[key] = value;
              }
            }
          }
        }
      } catch (e) {
        console.error('Error parsing body/files', e);
      }

      const searchParams = req.nextUrl.searchParams;
      const query: Record<string, any> = {};
      searchParams.forEach((value, key) => {
        query[key] = value;
      });

      // Next.js 16: context.params is a Promise and must be awaited
      const resolvedParams = context?.params ? await context.params : {};

      const mockReq = {
        body,
        query,
        files,
        params: resolvedParams,
        headers: {
          authorization: req.headers.get('authorization'),
        },
        user: (req as any).user, // Will be set by auth wrapper
      };

      // fn should return the NextResponse generated by sendResponse
      return await fn(mockReq, null, () => {});
    } catch (error) {
      return handleGlobalError(error);
    }
  };

export default catchAsync;
